### ISSUE TITLE
M1 mac build

### ISSUE THREAD

**Issue by jellohouse** [atom-community/atom#468] opened 2022-09-13 21:18 UTC
## Summary

It would be great to have an m1 (arm64) version for mac.

## Motivation

I came from this issue on the original atom repo:
https://github.com/atom/atom/issues/23500

Thinking it would be here for m1 native.

## Describe alternatives you've considered

Using atom (intel) mac.

## Additional context

No additional context.

**Comment by icecream17** [comment] 2022-09-14 04:40
I think this is a duplicate of https://github.com/atom-community/atom/issues/419 but let me know if it's not

**Closed by icecream17** 2022-09-14 04:40 UTC

**Comment by jellohouse** [comment] 2022-09-14 15:26
Ohh yep my bad I didn't see that - thanks!
